
CREATE TABLE LMSREPORTS.ACTIVITY_TYPE  ( 
	ACTIVITY_TYPE_ID  	NUMBER NOT NULL,
	ACTIVITY_TYPE_DESC	VARCHAR2(50) NOT NULL,
	LMS_KEY           	NUMBER NOT NULL,
	REV_BY            	VARCHAR2(25) DEFAULT USER NULL,
	REV_DT            	DATE DEFAULT SYSDATE NULL,
	PRIMARY KEY(ACTIVITY_TYPE_ID)
	NOT DEFERRABLE
	 VALIDATE
)
GO
