
CREATE TABLE LMSREPORTS.CAMPUS  ( 
	ID                  	NUMBER(9) NOT NULL,
	UCOPID              	VARCHAR2(50) NOT NULL,
	ABBRIEVIATION       	VARCHAR2(50) NOT NULL,
	NAME                	VARCHAR2(100) NOT NULL,
	DISPLAY_ABBREVIATION	VARCHAR2(50) NULL,
	CONSTRAINT CAMPUS_PK PRIMARY KEY(ID)
	NOT DEFERRABLE
	 VALIDATE
)
GO
