
create table LMSWEBSERVICE_METHODS(
METHOD_ID INT NOT NULL IDENTITY(1,1),
METHOD_NAME VARCHAR(50),
METHOD_DESCRIPTION VARCHAR(250),
PRIMARY KEY (METHOD_ID),
)

GO


create table LMSWEBSERVICE_USER_METHODS(
USER_METHOD_ID INT NOT NULL IDENTITY(1,1),
USER_ID int not null,
METHOD_ID INT not null,
PRIMARY KEY (USER_METHOD_ID),
foreign key (USER_ID) references lmswebservice_user(USER_ID),
foreign key (METHOD_ID) references lmswebservice_METHODS(METHOD_id)
)
GO


INSERT INTO LMSWEBSERVICE_METHODS (METHOD_NAME, METHOD_DESCRIPTION) VALUES ('Course Completions', 'Returns courses based on distinct course codes');
INSERT INTO LMSWEBSERVICE_METHODS (METHOD_NAME, METHOD_DESCRIPTION) VALUES ('Course CompletionsWC', 'Returns courses based on a wildcard list and optional date range');
INSERT INTO LMSWEBSERVICE_METHODS (METHOD_NAME, METHOD_DESCRIPTION) VALUES ('Course Completions Date Range', 'Returns courses based on a date range for a specific domain');

INSERT INTO LMSWEBSERVICE_USER_METHODS( USER_ID, METHOD_ID) VALUES (1, 1);
INSERT INTO LMSWEBSERVICE_USER_METHODS( USER_ID, METHOD_ID) VALUES (2, 1);
INSERT INTO LMSWEBSERVICE_USER_METHODS( USER_ID, METHOD_ID) VALUES (3, 2);
INSERT INTO LMSWEBSERVICE_USER_METHODS( USER_ID, METHOD_ID) VALUES (3, 3);


