USE LMSREPORTING

GO


CREATE TABLE LOCATION  ( 
	LOCATION_ID       	INT IDENTITY(1,1),
	LOCATION_CD       	VARCHAR(10) NULL,
	LOCATION_CD_HR    	VARCHAR(10) NULL,
	LOCATION_ABBR     	VARCHAR(10) NOT NULL,
	LOCATION_NAME     	VARCHAR(50) NOT NULL,
	LOCATION_NAME_LONG	VARCHAR(100) NULL,
	SHIB_ID_PROVIDER  	VARCHAR(100) NULL,
	LMS_KEY           	INT NOT NULL,
	TOP_LEVEL_LMS_KEY	INT NOT NULL,
	PRIMARY KEY(LOCATION_ID)
	)
GO
INSERT INTO LOCATION(LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES('00', 'OP', 'UCOP', 'UC Office President', 'University of California, Office of the President', 'urn:mace:incommon:ucop.edu', 3 ,3)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES('01', 'BK', 'UCB', 'UC Berkeley', 'University of California, Berkeley', 'urn:mace:incommon:berkeley.edu', 4,  4)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '02', 'SF', 'UCSF', 'UC San Francisco', 'University of California, San Francisco', 'urn:mace:incommon:ucsf.edu', 5,  5)
GO
INSERT INTO LOCATION(LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '03', 'DV', 'UCD', 'UC Davis', 'University of California, Davis', 'urn:mace:incommon:ucdavis.edu', 8,  8)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '04', 'LA', 'UCLA', 'UC Los Angeles', 'University of California, Los Angeles', 'urn:mace:incommon:ucla.edu', 11,  11)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '05', 'RV', 'UCR', 'UC Riverside', 'University of California, Riverside', 'urn:mace:incommon:ucr.edu', 14,  14)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '06', 'SD', 'UCSD', 'UC San Diego', 'University of California, San Diego', 'urn:mace:incommon:ucsd.edu', 15,  15)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '08', 'SB', 'UCSB', 'UC Santa Barbara', 'University of California, Santa Barbara', 'urn:mace:incommon:ucsb.edu', 19,  19)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '09', 'IR', 'UCI', 'UC Irvine', 'University of California, Irvine', 'urn:mace:incommon:uci.edu', 20,  20)
GO
INSERT INTO LOCATION(LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( '10', 'MC', 'UCM', 'UC Merced', 'University of California, Merced', 'urn:mace:incommon:ucmerced.edu', 23, 23)
GO
INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( NULL, NULL, 'LBNL', 'Lawrence Berkeley National Labs', 'Lawrence Berkeley National Labs', NULL, 24,  24)
GO

INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY,  TOP_LEVEL_LMS_KEY)
  VALUES( NULL, 'SC', 'UCSC', 'UC Santa Cruz', 'University of California, Santa Cruz', 'urn:mace:incommon:ucsc.edu', 18,  18)
GO

INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY, TOP_LEVEL_LMS_KEY)
  VALUES( NULL, null, 'UCSFMC', 'UCSF Medical Center', 'University of California, San Francsico Medical Center', null, 7, 5)
  go
  
  INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY, TOP_LEVEL_LMS_KEY)
  VALUES( NULL, null, 'UCLAMC', 'UCLA Medical Center', 'University of California, Los Angeles Medical Center', null, 13, 11)
GO


INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY, TOP_LEVEL_LMS_KEY)
  VALUES( NULL, null, 'UCSDMC', 'UCSD Medical Center', 'University of California, San Diego Medical Center', null, 10450, 15)
GO


INSERT INTO LOCATION( LOCATION_CD, LOCATION_CD_HR, LOCATION_ABBR, LOCATION_NAME, LOCATION_NAME_LONG, SHIB_ID_PROVIDER, LMS_KEY, TOP_LEVEL_LMS_KEY)
  VALUES( NULL, null, 'UCIMC', 'UCI Medical Center', 'University of California, Irvine Medical Center', null, 22, 20)
GO